#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


message="$(cat $1)"
requiredPattern="^(chore:|fix:|refactor:|optimise:|docs:|merge:|style:|add:|feat:|perf:|breaking_change:) .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>:<what was done>"
  echo "Allowed verbs in imperative mood: fix:, feat:, breaking_change:, merge:"
  echo "Example: feat:add login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi